screenshot:
  globaltimeout: 60000 # Maximal time a request for a screenshot can take.
  timeout: 10000 # Time in ms, maximal time to wait until the main page is fully loaded
  iframetimeout: 2000 # Time in ms, maximal time to wait for an iframe to load.
  showwindow: true
  maxheight: 0
cache:
  folder: "cache"