screenshot:
  width: 1024
  maxwidth: 3000
  height: 600
  maxheight: 3000
  format: "png" # default format
  allowedformat: # allowed formate
    - 'png'
  delay: 0
  maxdelay: 10000
  scrollbar: false
  page: false
  transparent: false
  css: ""
server:
  domain:"http://localhost"
  port: 8080
  cors: true
  kue:
    show: true
    username: 'default'
    password: 'default'
cache:
  folder:"cache"
  reload:true
  ttl: 3600000