logging: # These options are directly passed to winston
  filename: "runtime.log"
  level: "verbose" #npm style logging
  json: false
screenshot:
  timeout: 10000 # Time in ms, maximal time to wait until the main page is fully loaded
  iframetimeout: 2000 # Time in ms, maximal time to wait for an iframe to load.
  showwindow: true
  url: # These options can be configured via the URL request
    width: 1024
    maxwidth: 3000
    height: 600
    maxheight: 3000
    format: "png" # default format
    allowedformat: # allowed formate
      - 'jpeg'
      - 'png'
    delay: 0
    maxdelay: 10000
    scrollbar: false
    fullpage: false
cacheService:
  folder: "tmp"
  reload: true
  ttl: 60000 # Time in ms 0 means cache forever
server:
  port: 8080
  cors: true